=== Guille-Lavado/0503-Validacion-XML-DTD-III/Ejercicio 1/marcadores_CUENTOS.dtd
<!ELEMENT cuento (personajes, trama, etiqueta?)>
<!ATTLIST cuento
  cod CDATA #REQUIRED
  titulo CDATA #REQUIRED>

<!ELEMENT personajes (personaje+)>
<!ELEMENT personaje (nombre, genero, (descripcion_fisica|imagen|url)?)>
<!ATTLIST personaje
  id ID #REQUIRED
  tipo (principal|secundario|antagonista) "principal">

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT descripcion_fisica (#PCDATA)>
<!ELEMENT imagen EMPTY>
<!ATTLIST imagen
  src CDATA #REQUIRED>
  
<!ELEMENT url EMPTY>
<!ATTLIST url
  href CDATA #REQUIRED>

<!ELEMENT trama (#PCDATA)>
<!ELEMENT etiqueta EMPTY>
<!ATTLIST etiqueta
  nombre CDATA #REQUIRED>

=== Guille-Lavado/0503-Validacion-XML-DTD-III/Ejercicio 1/CUENTO2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cuento SYSTEM "marcadores_CUENTOS.dtd">
<cuento cod="B02" titulo="El Dragón de las Sombras">
    <personajes>
        <personaje id="d1">
            <nombre>Dragón Sombrio</nombre>
            <genero>N</genero>
        </personaje>
        <personaje id="h1">
            <nombre>Héroe del Alba</nombre>
            <genero>M</genero>
        </personaje>
    </personajes>
    <trama>Un héroe debe derrotar al dragón que amenaza con sumir el mundo en oscuridad eterna.</trama>
    <etiqueta nombre="hadas"/>
</cuento>

=== Guille-Lavado/0503-Validacion-XML-DTD-III/Ejercicio 1/CUENTO1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Nombre: Guillermo Lavado 
Curso: DAW1 
Fecha: 02/04/2025 
Ejercicio: ejercicio1
-->
<!DOCTYPE cuento SYSTEM "marcadores_CUENTOS.dtd">
<cuento cod="A01" titulo="La Cenicienta">
    <personajes>
        <personaje id="p1"  tipo="principal">
            <nombre>Cenicienta</nombre>
            <genero>F</genero>
        </personaje>
        <personaje id="p2"  tipo="antagonista">
            <nombre>Madrastra</nombre>
            <genero>F</genero>
        </personaje>
        <personaje id="p3">
            <nombre>Príncipe</nombre>
            <genero>M</genero>
        </personaje>
    </personajes>
    <trama>Una joven maltratada por su madrastra asiste al baile del príncipe con ayuda de su hada madrina.</trama>
    <etiqueta nombre="clásico"/>
</cuento>
